#  Simple workflow for get the latex pdf
name: Sphinx pdf

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:    
      - 'main'
    paths:
      - 'docs/**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies with pip
        run: pip install --upgrade -r docs/requirements.txt
      
      - name: Install latex and fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk texlive-lang-spanish

          mkdir -p ~/.local/share/
          cp -r docs/fonts ~/.local/share/
          fc-cache -f -v
      
      - name: Build the docs
        run: |
          cd docs
          make latexpdf
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: ./docs/build/latex/vehculodemuestro.pdf
