#  Simple workflow for deploying from sphinx to GitHub Pages
name: Sphinx build

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: cd docs
      - name: Install dependencies with pip
        run: |
          
          pip install --no-warn-script-location --user --upgrade -r requirements.txt
      - name: Build the docs
        run: make html # && make latexpdf
      
      - name: Check style
        run: make test

      # push the generated content into the `main` (former `master`) branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html