#  Simple workflow for deploying from sphinx to GitHub Pages
name: Sphinx build

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main 
      - docs/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies with pip
        run: pip install --upgrade -r docs/requirements.txt

      - name: Build the docs
        run: |
          cd docs 
          make html # && make latexpdf
      
      - name: Check style
        run: |
          cd docs 
          make test

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: webapp-artifact
          path: ./docs/build/html/

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: webapp-artifact

      - name: Upload to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./webapp-artifact

      - run: touch .nojekyll

  deploy:
    needs: upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2