#  Simple workflow for deploying from sphinx to GitHub Pages
name: Sphinx build

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main 
      - docs/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with pip
        run: pip install --upgrade -r docs/requirements.txt
      - name: Build the docs
        run: |
          cd docs 
          make html # && make latexpdf
      
      - name: Check style
        run: |
          cd docs 
          make test

      - run: mkdir -p /src

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: webapp-artifact
          path: /src

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: webapp-artifact
          path: /src

      - name: Checkout
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src